version: "3"

services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_USER=re7
      - POSTGRES_PASSWORD=re7
      - POSTGRES_DB=re7
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - ./.env
    environment:
      - PORT=80
      - DATABASE_URL=postgresql://re7:re7@db:5432/re7
      - CORS_ORIGIN_WHITELIST=http://localhost:9091,http://localhost:3000,http://127.0.0.1:9091,http://127.0.0.1:3000
    ports:
      - 9090:80
    depends_on:
      - db

volumes:
  data:
